![image.png](attachment:image.png)

# Numpy

Numpy is THE library for scientific computing and linear algebra in Python's community and was designed to give users the best of both worlds in programming languages: the speed of `C` language with the readability and elegance of `Python`.

### Why Numpy?
A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example we cannot multiply two lists directly we will have to do it element wise. This is where the role of NumPy comes into play.

In [1]:
from numpy import *
import numpy as np

Very quick speed comparison to show the staggering difference in performance, don't bother about the code in the following cell.

In [ ]:
import numpy as np
import time
import gc # garbage collection
import sys


def compare_times(f1, f2, setup1=None, setup2=None, runs=30):
    print('    format: mean seconds (standard error)', runs, 'runs')
    maxpad = max(len(f.__name__) for f in (f1, f2))
    means = []
    for setup, f in [[setup1, f1], [setup2, f2]]:
        setup = (lambda: tuple()) if setup is None else setup

        total_times = []
        for _ in range(runs):
            try:
                gc.disable()
                args = setup()

                start = time.time()
                if isinstance(args, tuple):
                    f(*args)
                else:
                    f(args)
                end = time.time()

                total_times.append(end - start)
            finally:
                gc.enable()

        mean = np.mean(total_times)
        se = np.std(total_times) / np.sqrt(len(total_times))
        print('    {} {:.2e} ({:.2e})'.format(f.__name__.ljust(maxpad), mean, se))
        means.append(mean)
    print('    improvement ratio {:.1f}'.format(means[0] / means[1]))

In [ ]:
size = 10 ** 7
print('create a list 1, 2, ...', size)


def create_list(): return list(range(size))
def create_array(): return np.arange(size, dtype=int)

compare_times(create_list, create_array)

create a list 1, 2, ... 10000000
    format: mean seconds (standard error) 30 runs
    create_list  4.85e-01 (1.10e-02)
    create_array 2.39e-02 (6.99e-04)
    improvement ratio 20.3


In [ ]:
import time
num = 10000000
a = np.random.random(num)
b = np.random.random(num)

star = time.time()
c = np.dot(a,b)
en = time.time()
print(c)
print("Verctorize  : " +  str((en -star)*1000) + 'ms')

d =0
start = time.time()
for i in range(num):
    d += a[i]*b[i]
end = time.time()

print(d)
print("Loop version  : " +  str((end -start)*1000) + 'ms')
print("Vectorization is faster by" , (end -start)/(en -star) , 'times')

2499632.0268662428
Verctorize  : 12.294769287109375ms
2499632.026866403
Loop version  : 4796.185493469238ms
Vectorization is faster by 390.0996742165684 times


### Convinced about numpy powers? ... Now, let's practice!

#### Q1: Create a 1D array of numbers from 0 to 9.


In [17]:
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q2: Extract all odd numbers from arr.


In [18]:
odd=arr1[arr1%2 != 0]
odd

array([1, 3, 5, 7, 9])

#### Q3: Replace all odd numbers in arr with -1.


In [22]:
odd[odd %2 !=0]=-1
odd

array([-1, -1, -1, -1, -1])

#### Q4: Convert a 1D array of length 10 to a 2D array with 2 rows


In [23]:
new_size=[2,5]
new_arr1=np.resize(arr1,new_size)
new_arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Q5: compute the square root for each element in the  array
#### ([[1, 2, 3],[2, 3, 4],[4, 5, 6]])


In [2]:
arr2=np.array([[1, 2, 3],[2, 3, 4],[4, 5, 6]])
arr2_sqr=np.multiply(arr2,arr2)
arr2_sqr

array([[ 1,  4,  9],
       [ 4,  9, 16],
       [16, 25, 36]])

#### Q6: compute the exponential for each element in the above array


In [7]:
arr2_exp=np.exp(arr2_sqr)
arr2_exp

array([[2.71828183e+00, 5.45981500e+01, 8.10308393e+03],
       [5.45981500e+01, 8.10308393e+03, 8.88611052e+06],
       [8.88611052e+06, 7.20048993e+10, 4.31123155e+15]])

#### Q7: sample 8 elements from uniform dist ([0, 1)


In [13]:
arr3=np.linspace(0,1,8)
arr3=around(arr3,4)
arr3

array([0.    , 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571, 1.    ])

#### Q8: Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [17]:
#aarr4=np.arange(0,10,2)
arr42=np.random.randint(0,10,5)
arr42

array([8, 9, 0, 1, 6])

#### Q9: Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [18]:
arr5=np.random.randint(10,21,(3,4))
arr5

array([[11, 16, 20, 13],
       [15, 12, 18, 13],
       [12, 12, 13, 16]])

#### Q10: Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [19]:
arr6=np.random.randint(5,50,10)
arr6

array([14, 26, 37, 42,  5, 31, 34, 20, 26, 13])

#### Q11: Write a NumPy program to create an array of all the even integers from 30 to 70.

In [22]:
arr7=np.arange(30,71)
print(arr7)
arr7_eve=arr7[arr7% 2==0]
arr7_eve

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#### Q12: Write a NumPy program to check whether two arrays are equal (element wise) or not

In [40]:
array1=np.arange(2,10,2)
array2=np.arange(2,10,2)
equal=(array1==array2).all()
print(equal)
if equal:
    print("element wise")
else:
    print("not element wise")

True
element wise


In [32]:
np.array_equal?

* further reading: [visit here](https://www.w3resource.com/python-exercises/numpy/index.php)